server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

#Eureka
  eureka:
    client:
      serviceUrl:
        defaultzone: ${EUREKA_SERVER:http://registry-discovery:8761/eureka/}
      register-with-eureka: true
      healthcheck:
        enabled:  true
      fetch-registry: true

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: ms-product_update
          uri: lb://ms-product #http://localhost:8085 lb://ms-product
          predicates:
            - Path=/ms-product/v1/product/update/**
            - Method=PUT
          filters:
            - name: AuthenticationFiltering

        - id: ms-product
          uri: lb://ms-product #http://localhost:8085 lb://ms-product
          predicates:
            - Path=/ms-product/v1/product/**
          #filters:
          #  - name: AuthenticationFiltering
